### ISSUE TITLE
Stuck in Google account picker loop

### ISSUE THREAD

**Issue by kmcital** [getgrav/grav-plugin-login-oauth#18]
A setup using no login path in the Login plugin settings seems to work if I have all the redirect URI's added to my google API credentials, but when I use the login path (eg. /login) so that I only have to use one redirect URI (eg. www.mysite.com/login) then I get stuck during authorization in a loop where I pick my google account and it redirects, redirects and then goes back to picking a google account (that's on Safari). On Chrome, I get "accounts.google.com redirected you too many times."

I deleted my Google API credentials and redeployed a new Google credentials, cleared cookies and tried again. No luck.

**Comment by Vivalldi** [comment]
@kmcital what does your config file look like? (please comment out API keys).

**Comment by kmcital** [comment]
@Vivalldi here you go...

**login-oauth.yaml:**
```
enabled: true
built_in_css: true
providers:
  Facebook:
    enabled: false
    enable_email: false
  Google:
    enabled: true
    credentials:
      key: xxxxxxxxxx
      secret: xxxxxxxxxxx
    whitelist:
      - mydomain.com
  GitHub:
    enabled: false
  Twitter:
    enabled: false
  Linkedin:
    enabled: false
```

**login.yaml** (with current workaround of no login route path specified, otherwise I would add `/login`):
```
enabled: true
built_in_css: true
route_activate: /activate_user
route_forgot: /forgot_password
route_reset: /reset_password
route_profile: /user_profile
route_register: /user_register
parent_acl: true
protect_protected_page_media: false
user_registration:
  enabled: true
  fields:
    - username
    - password
    - email
    - fullname
    - title
  access:
    site:
      login: 'true'
  options:
    validate_password1_and_password2: true
    set_user_disabled: false
    login_after_registration: true
    send_activation_email: false
    send_notification_email: false
    send_welcome_email: '1'
rememberme:
  enabled: true
  timeout: 604800
  name: grav-rememberme
max_pw_resets_count: 0
max_pw_resets_interval: 60
max_login_count: 0
max_login_interval: 2
```
